### ISSUE TITLE
Generate cmmn.json based on cmmn meta model

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/cmmn-moddle#1]
Right now we've hand built the model.

We should follow a similar approach to [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle) and [generated](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/adapter/cmof/generate-simple.js) the model from the CMMN meta-model.

**Comment by nikku** [comment]
We'll not do this any time soon.
